package com.rentflow.staff;

public enum Permission {
    FLEET_VIEW, FLEET_CREATE, FLEET_EDIT, FLEET_DELETE,
    RESERVATION_VIEW, RESERVATION_CREATE, RESERVATION_EDIT,
    RESERVATION_CANCEL, RESERVATION_APPROVE_DISCOUNT,
    CUSTOMER_VIEW, CUSTOMER_CREATE, CUSTOMER_EDIT, CUSTOMER_BLACKLIST,
    CONTRACT_VIEW, CONTRACT_CREATE, CONTRACT_CLOSE,
    PAYMENT_VIEW, PAYMENT_RECORD, PAYMENT_REFUND_APPROVE,
    MAINTENANCE_VIEW, MAINTENANCE_CREATE, MAINTENANCE_EDIT,
    STAFF_VIEW, STAFF_MANAGE, ROLE_MANAGE,
    REPORT_VIEW, REPORT_EXPORT,
    SETTINGS_VIEW, SETTINGS_EDIT
}
