package com.rentflow.notification;

public enum NotificationTrigger {
    RESERVATION_CREATED,
    RESERVATION_CONFIRMED,
    RESERVATION_CANCELLED,
    CONTRACT_OPENED,
    PICKUP_RECORDED,
    RETURN_RECORDED,
    INVOICE_SENT,
    INVOICE_PAID,
    DEPOSIT_RELEASED,
    DOCUMENT_EXPIRING,
    MAINTENANCE_DUE,
    RETURN_OVERDUE
}
